# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://mincong.io  # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Mincong Huang
description: >  # this means to ignore newlines until "Language & timezone"
  Hi, welcome to my blog! I'm a software engineer at Vertesia. I write blog posts
  in my free time. My blogs are
  bits and pieces of my tech journey. Most of them are related
  to Java. Hope you enjoy them! My opinions are my own, not Vertesia's. This blog
  is powered by Jekyll, a simple, blog-aware, static sites solution.

## => Language and Timezone
##############################
lang: en  # the language of your site, default as "en"
timezone: Europe/Paris  # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Mincong Huang
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     : mincong.h@gmail.com
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : mincong_h      # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : '@mincong' # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : mincong-huang  # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : mincong-h      # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

# Jekyll SEO Tag
twitter:
  username: mincong_h
  card:     summary_large_image

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: mincong-h/mincong-h.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : /en/archive/
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true

## Chart
chart: # false (default), true


## => Paginate (v2)
##############################
## paginate v1 does not support pagination for all collections, e.g. "cn"
pagination:
  enabled: true
  per_page: 8


## => Sources
##############################
sources: custom # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: disqus # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: mincong-h # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: nanosearch # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google  # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : UA-87129300-1  # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics

  datadog:
    client_token: pub1212981d8cc6f0997eb39addafaefc3d
    application_id: bc39e1cb-2fe4-4ba3-aa97-e077d1593720
    site: datadoghq.eu
    service: mincong.io

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /en/:title/

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true
  - scope:
      path: _cn
      type: cn
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

## => Collections
##############################
collections:
  # Categories are a collection that contains many articles. The articles of
  # one category should be very different from the articles from another
  # category. One article should avoid having more than 2 categories. It
  # represents an important part of your technical stack (skill-tree).
  # Examples: build, java, python
  displayed_en_categories:
    my_label:  Categories
    permalink: /en/categories/:name/
    output:    true
  displayed_cn_categories:
    my_label:  文章类别
    permalink: /cn/categories/:name/
    output:    true
  
  en_projects:
    my_label:  Projects
    permalink: /en/projects/:name/
    output:    true

  # Series are a collection that contains several articles. A series explains
  # one target topic from different angles. It is usually about a framework or
  # a project.
  series:
    my_label:  Series
    permalink: /en/series/:name/
    output:    true
  cn:
    promalink: /cn/:title/
    output:    true
