#
# https://www.mydatahack.com/deploying-jekyll-site-to-github-page-with-github-actions/
# https://github.com/JamesIves/github-pages-deploy-action
#
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - docker # testing

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set service version
      run: |
        echo "SERVICE_VERSION=v${GITHUB_RUN_ID}-${GITHUB_SHA::7}"
        echo "SERVICE_VERSION=v${GITHUB_RUN_ID}-${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v2
    - name: Build Jekyll website
      run: |
         bundle exec jekyll build --trace --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        SERVICE_VERSION: "${{ env.SERVICE_VERSION }}"
        BS_USERNAME: "${{ secrets.BS_USERNAME }}"
        BS_PASSWORD: "${{ secrets.BS_PASSWORD }}"
        BS_ENABLED: true
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
